spring.application.name=SkillSwaps
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/skillswap
spring.datasource.username=postgres
spring.datasource.password=Yash@DB

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port (Optional)
server.port=8080

jwt.secret=TYEOODJGNH123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ

#24 hours
jwt.expiration=86400000 